version: "3"
services:

  consul:
    image: consul:latest
    hostname: consul
    restart: on-failure
    ports:
      - "8500:8500"
    command:
      - "consul"
      - "agent"
      - "-server"
      - "-bootstrap-expect=1"
      - "-node=agent-one"
      - "-ui"
      - "-data-dir=/consul/data"
      - "-client=0.0.0.0"
      - "-config-dir=/consul/config"
    environment:
      CONSUL_BIND_INTERFACE: eth0
    volumes:
      - ".docker/volumes/consul:/consul/data"

  #todo Регистратор не в состоянии подчищать за собой неработающие сервисы, чем захламляет консул
  registrator:
    image: gliderlabs/registrator:latest
    restart: on-failure
    depends_on:
      - consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command:
      - "-cleanup=true"
      - "-ip=${MY_IP}"
      - "consul://consul:8500"

  content:
    image: content:latest
    build:
        context: content
    depends_on:
      - postgres_db
      - rabbitmq
      - consul
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "http://127.0.0.1:8080/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 50

  executor:
    image: executor:latest
    build:
      context: executor
    depends_on:
      - content
      - rabbitmq
      - consul
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONSUL_CONFIG_FORMAT=yaml
    ports:
      - "8020:8020"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "http://127.0.0.1:8020/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 50

  scheduler:
    image: scheduler:latest
    build:
      context: scheduler
    depends_on:
      - scheduler_postgres_db
      - rabbitmq
      - consul
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONSUL_CONFIG_FORMAT=yaml
    ports:
      - "8040:8040"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "http://127.0.0.1:8040/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 50

  postgres_db:
    image: postgres:11.8
    environment:
      - POSTGRES_DB=compose-postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U compose-postgres -d compose-postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  scheduler_postgres_db:
    image: postgres:11.8
    environment:
      - POSTGRES_DB=compose-postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5434:5432"
    volumes:
      - ./scheduler_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U compose-postgres -d compose-postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.11.6-management
    hostname: rabbitmq
    restart: on-failure
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"