version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ".docker/volumes/mysql:/var/lib/mysql"
      - ".docker/dev/mysql/init:/docker-entrypoint-initdb.d"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"

  zookeeper:
    profiles:
      - infra
    image: confluentinc/cp-zookeeper:5.0.0
    restart: on-failure
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    profiles:
      - infra
    image: confluentinc/cp-kafka:5.0.0
    restart: on-failure
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OPTS: -Dauto.create.topics.enabled=true
    depends_on:
      - zookeeper