version: "3"
services:

  content:
    image: content:latest
    build:
        context: content
    container_name: content
    depends_on:
      - postgres_db
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=PLAINTEXT://kafka:9092
    ports:
      - "8080:8080"
    restart: unless-stopped

  executor:
    image: executor:latest
    build:
      context: executor
    container_name: executor
    depends_on:
      - content
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=PLAINTEXT://kafka:9092
    restart: unless-stopped

  scheduler:
    image: scheduler:latest
    build:
      context: scheduler
    container_name: scheduler
    depends_on:
      - executor
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=PLAINTEXT://kafka:9092
    restart: unless-stopped

  postgres_db:
    image: postgres:11.8
    container_name: postgres_db
    environment:
      - POSTGRES_DB=compose-postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U compose-postgres -d compose-postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5.7
    depends_on:
      - postgres_db
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@test.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    restart: on-failure
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    restart: on-failure
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OPTS: -Dauto.create.topics.enabled=true
    depends_on:
      - zookeeper