spring:
  profiles:
    active: ${ENV}

  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          time_zone: UTC
    open-in-view: false

  datasource:
    url: jdbc:postgresql://postgres:5432/compose-postgres
    username: root
    password: root

  cloud:
    stream:
      function:
        definition: actionDeleteEventConsumer;actionTimeoutCreateEventConsumer;

      bindings:
        actionTimeoutBatchEventProducer-out-0:
          destination: action-timeout

        actionDeleteEventConsumer-in-0:
          destination: action-delete

        actionTimeoutCreateEventConsumer-in-0:
          destination: action-timeout-create

      poller:
        fixed-delay: 2
        time-unit: seconds

      default-binder: rabbit

  rabbitmq:
    host: rabbitmq

logging:
  level:
    com:
      newestworld: debug