spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - "127.0.0.1:9092"
            - ${KAFKA_ADDR}
          auto-add-partitions: true
          auto-create-topics: true
          replication-factor: 1
          min-partition-count: 1
          required-acks: 1
      bindings:
        action-timeout:
          destination: action-timeout
          group: executor
          binder: kafka
          consumer:
            autoRebalanceEnabled: true
            autoCommitOnError: false

      default-binder: kafka