spring:
  profiles:
    active: ${ENV}

  cloud:
    stream:
      function:
        definition: actionTimeoutBatchEventConsumer;actionDataBatchEventConsumer;

      bindings:
        actionTimeoutBatchEventConsumer-in-0:
          destination: action-timeout

        actionDataBatchEventConsumer-in-0:
          destination: action-data

        actionDeletedEventProducer-out-0:
          destination: action-deleted

        factoryUpdateEventProducer-out-0:
          destination: factory-update

        actionCreateEventProducer-out-0:
          destination: action-create

        actionDataRequestBatchEventProducer-out-0:
          destination: action-data-request

      default-binder: rabbit

  rabbitmq:
    host: rabbitmq

logging:
  level:
    com:
      newestworld: debug