spring:
  profiles:
    active: ${ENV}

  cloud:
    stream:
      function:
        definition: consumerActionTimeoutBatchEvent

      bindings:
        consumerActionTimeoutBatchEvent-in-0:
          destination: action-timeout

        producerActionDeletedEvent-out-0:
          destination: action-deleted

      kafka:
        bindings:
          actionTimeoutConsumer-in-0:
            consumer:
              ack-mode: manual
        binder:
          brokers:
            - "127.0.0.1:9092"
            - ${KAFKA_ADDR}
          auto-add-partitions: true
          auto-create-topics: true
          replication-factor: 1
          min-partition-count: 1
          required-acks: 1

      default-binder: kafka

logging:
  level:
    com:
      newestworld: debug